### ISSUE TITLE
Unicode decode error

### ISSUE THREAD

**Issue by navinmaxx** [karanveerm/quizgen#6]
while generating quiz (in Hindi Language )their is an error comes plz help
C:\Users\nav\Desktop\quizgen-master\quizgen-master>python quizgen.py new1.quiz
Traceback (most recent call last):
  File "quizgen.py", line 797, in <module>
    main()
  File "quizgen.py", line 519, in main
    quiz = quiz_parser.parse()
  File "quizgen.py", line 168, in parse
    lines = quizfile.readlines()
  File "C:\Users\nav\AppData\Local\Programs\Python\Python37-32\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 31: character maps to <undefined>
![qqq](https://user-images.githubusercontent.com/55912686/65814402-ddc30880-e1fe-11e9-91b2-ce0980c4727d.jpg)

**Comment by jakiro2017** [comment]
Hi please upload your small quiz so I can test.
Or you can test this branch: https://github.com/jakiro2017/quizgen.git
If Ok I will create pr #8  with the author

**Comment by navinmaxx** [comment]
https://quizzzpopppp.000webhostapp.com/Untitled.html  i need this exactly this type of quiz can u help

**Comment by jakiro2017** [comment]
> https://quizzzpopppp.000webhostapp.com/Untitled.html i need this exactly this type of quiz can u help

Hi this is not the same as your original question, the quiz only contain English and the question mechanism different from quizgen. => This I can't help

However, I see your quiz is just simple text quiz, I suggest you use Google Form or Savsoft quiz to do your test

**Comment by jakiro2017** [comment]
Since PR #8 is merged, you should close this issue.
